Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$sourceDir = Join-Path $scriptDir "source"
$assetsDir = Join-Path $scriptDir "assets"
$dataDir   = Join-Path (Split-Path -Parent $scriptDir) "Data\prog\win\bin"

# Read whitepath.txt (generated by Nova Chrysalia alongside Setup.bat)
# Contains the path to the game's white_data root directory.
$gameBinDir = $null
$whitePathFile = Join-Path $scriptDir "whitepath.txt"
if ([System.IO.File]::Exists($whitePathFile)) {
    $whitePath = (Get-Content $whitePathFile -Raw).Trim()
    if ($whitePath) {
        $gameBinDir = [System.IO.Path]::Combine($whitePath, "prog\win\bin")
    }
}

# ---------------------------------------------------------------------------
# Theme
# ---------------------------------------------------------------------------
$clrBg      = [System.Drawing.Color]::FromArgb(18, 18, 28)
$clrPanel   = [System.Drawing.Color]::FromArgb(28, 28, 42)
$clrAccent  = [System.Drawing.Color]::FromArgb(190, 150, 60)
$clrText    = [System.Drawing.Color]::White
$clrSub     = [System.Drawing.Color]::FromArgb(170, 170, 195)
$clrBtn     = [System.Drawing.Color]::FromArgb(48, 48, 68)
$fntTitle   = New-Object System.Drawing.Font("Segoe UI", 13, [System.Drawing.FontStyle]::Bold)
$fntHdr     = New-Object System.Drawing.Font("Segoe UI", 10, [System.Drawing.FontStyle]::Bold)
$fntBody    = New-Object System.Drawing.Font("Segoe UI",  9)
$fntSmall   = New-Object System.Drawing.Font("Segoe UI",  8)

# ---------------------------------------------------------------------------
# Choices
# ---------------------------------------------------------------------------
$choices = [ordered]@{
    Language    = "latin"
    Maps        = "sharp"
    Savefiles   = "original"
}

# ---------------------------------------------------------------------------
# Step definitions (ASCII only)
# ---------------------------------------------------------------------------
$steps = @(
    [ordered]@{
        Key  = "Language"
        Title = "Language"
        Desc  = "Select which language fonts to use for menus and subtitles."
        Opts  = @(
            [ordered]@{ Val = "latin";   Label = "Latin + Japanese"; Detail = "English, French, German, Italian, Spanish, and Japanese." }
            [ordered]@{ Val = "chinese"; Label = "Chinese";          Detail = "Simplified Chinese HD font replacement." }
            [ordered]@{ Val = "korean";  Label = "Korean";           Detail = "Korean HD font replacement." }
        )
        Imgs  = $null
    }
    [ordered]@{
        Key  = "Maps"
        Title = "Map Style"
        Desc  = "Choose the rendering style for world map and area map textures."
        Opts  = @(
            [ordered]@{ Val = "sharp";  Label = "Sharp-scaled"; Detail = "Crisp, pixel-accurate upscale that preserves hard edges and fine linework." }
            [ordered]@{ Val = "smooth"; Label = "Smooth";        Detail = "Soft filtering applied to map textures for a cleaner, less pixelated look." }
        )
        Imgs  = @("maps_sharp.png", "maps_smooth.png")
    }
    [ordered]@{
        Key  = "Savefiles"
        Title = "Save File Style"
        Desc  = "Choose the artwork style used on save file screens."
        Opts  = @(
            [ordered]@{ Val = "original"; Label = "HD Original";      Detail = "High-resolution recreation of the original save file icons." }
            [ordered]@{ Val = "artwork";  Label = "Artwork Backdrops"; Detail = "Official artwork used as backgrounds." }
        )
        Imgs  = @("savefiles_original.png", "savefiles_artwork.png")
    }
)

# ---------------------------------------------------------------------------
# Helper: load image from assets\ (returns $null silently if missing)
# ---------------------------------------------------------------------------
function Load-Asset($filename) {
    if (-not $filename) { return $null }
    $p = Join-Path $assetsDir $filename
    if ([System.IO.File]::Exists($p)) {
        try { return [System.Drawing.Image]::FromFile($p) } catch {}
    }
    return $null
}

# ---------------------------------------------------------------------------
# Build form
# ---------------------------------------------------------------------------
$form = New-Object System.Windows.Forms.Form
$form.Text            = "FF XIII HD Mod - Installation"
$form.ClientSize      = New-Object System.Drawing.Size(720, 480)
$form.FormBorderStyle = "FixedSingle"
$form.MaximizeBox     = $false
$form.StartPosition   = "CenterScreen"
$form.BackColor       = $clrBg

# Header bar
$pnlHeader = New-Object System.Windows.Forms.Panel
$pnlHeader.SetBounds(0, 0, 720, 56)
$pnlHeader.BackColor = $clrPanel
$form.Controls.Add($pnlHeader)

$lblTitle = New-Object System.Windows.Forms.Label
$lblTitle.SetBounds(20, 10, 500, 36)
$lblTitle.Text      = "FF XIII HD Mod"
$lblTitle.Font      = $fntTitle
$lblTitle.ForeColor = $clrAccent
$lblTitle.BackColor = [System.Drawing.Color]::Transparent
$pnlHeader.Controls.Add($lblTitle)

# Left panel (steps)
$pnlLeft = New-Object System.Windows.Forms.Panel
$pnlLeft.SetBounds(0, 56, 440, 374)
$pnlLeft.BackColor = $clrBg
$form.Controls.Add($pnlLeft)

$lblStepTitle = New-Object System.Windows.Forms.Label
$lblStepTitle.SetBounds(20, 20, 400, 30)
$lblStepTitle.Font      = $fntHdr
$lblStepTitle.ForeColor = $clrText
$lblStepTitle.BackColor = [System.Drawing.Color]::Transparent
$pnlLeft.Controls.Add($lblStepTitle)

$lblStepDesc = New-Object System.Windows.Forms.Label
$lblStepDesc.SetBounds(20, 54, 400, 40)
$lblStepDesc.Font      = $fntBody
$lblStepDesc.ForeColor = $clrSub
$lblStepDesc.BackColor = [System.Drawing.Color]::Transparent
$pnlLeft.Controls.Add($lblStepDesc)

$pnlRadios = New-Object System.Windows.Forms.Panel
$pnlRadios.SetBounds(20, 100, 400, 240)
$pnlRadios.BackColor = [System.Drawing.Color]::Transparent
$pnlLeft.Controls.Add($pnlRadios)

# Right panel (preview)
$pnlRight = New-Object System.Windows.Forms.Panel
$pnlRight.SetBounds(440, 56, 280, 374)
$pnlRight.BackColor = $clrPanel
$form.Controls.Add($pnlRight)

$pic = New-Object System.Windows.Forms.PictureBox
$pic.SetBounds(10, 10, 260, 354)
$pic.SizeMode  = "Zoom"
$pic.BackColor = $clrPanel
$pic.Visible   = $false
$pnlRight.Controls.Add($pic)

$lblNoPic = New-Object System.Windows.Forms.Label
$lblNoPic.SetBounds(10, 160, 260, 40)
$lblNoPic.Text      = "No preview available"
$lblNoPic.Font      = $fntSmall
$lblNoPic.ForeColor = [System.Drawing.Color]::FromArgb(80, 80, 100)
$lblNoPic.BackColor = [System.Drawing.Color]::Transparent
$lblNoPic.TextAlign = "MiddleCenter"
$pnlRight.Controls.Add($lblNoPic)

# Bottom bar
$pnlBottom = New-Object System.Windows.Forms.Panel
$pnlBottom.SetBounds(0, 430, 720, 50)
$pnlBottom.BackColor = $clrPanel
$form.Controls.Add($pnlBottom)

function Make-Button($text, $x) {
    $b = New-Object System.Windows.Forms.Button
    $b.SetBounds($x, 8, 110, 34)
    $b.Text      = $text
    $b.Font      = $fntBody
    $b.ForeColor = $clrText
    $b.BackColor = $clrBtn
    $b.FlatStyle = "Flat"
    $b.FlatAppearance.BorderColor = $clrAccent
    $b.FlatAppearance.BorderSize  = 1
    $pnlBottom.Controls.Add($b)
    return $b
}

$btnBack    = Make-Button "< Back"   480
$btnNext    = Make-Button "Next >"   600
$btnInstall = Make-Button "Install"  600
$btnInstall.Visible = $false

# Step dots
$script:dots = @()
for ($i = 0; $i -lt $steps.Count; $i++) {
    $d = New-Object System.Windows.Forms.Label
    $d.Size      = New-Object System.Drawing.Size(10, 10)
    $d.Location  = New-Object System.Drawing.Point((20 + $i * 16), 20)
    $d.BackColor = [System.Drawing.Color]::FromArgb(60, 60, 80)
    $pnlBottom.Controls.Add($d)
    $script:dots += $d
}

function Set-Dots {
    for ($i = 0; $i -lt $script:dots.Count; $i++) {
        $script:dots[$i].BackColor = if ($i -eq $script:page) { $clrAccent } else { [System.Drawing.Color]::FromArgb(60, 60, 80) }
    }
}

# Confirmation panel
$pnlConfirm = New-Object System.Windows.Forms.Panel
$pnlConfirm.SetBounds(0, 56, 720, 374)
$pnlConfirm.BackColor = $clrBg
$pnlConfirm.Visible   = $false
$form.Controls.Add($pnlConfirm)

$lblConfirmHdr = New-Object System.Windows.Forms.Label
$lblConfirmHdr.SetBounds(20, 20, 680, 30)
$lblConfirmHdr.Text      = "Ready to install"
$lblConfirmHdr.Font      = $fntHdr
$lblConfirmHdr.ForeColor = $clrAccent
$lblConfirmHdr.BackColor = [System.Drawing.Color]::Transparent
$pnlConfirm.Controls.Add($lblConfirmHdr)

$lblConfirmBody = New-Object System.Windows.Forms.Label
$lblConfirmBody.SetBounds(20, 60, 680, 280)
$lblConfirmBody.Font      = $fntBody
$lblConfirmBody.ForeColor = $clrText
$lblConfirmBody.BackColor = [System.Drawing.Color]::Transparent
$pnlConfirm.Controls.Add($lblConfirmBody)

# ---------------------------------------------------------------------------
# Page state
# ---------------------------------------------------------------------------
$script:page = 0

function Show-Step($idx) {
    $step = $steps[$idx]
    $lblStepTitle.Text = $step.Title
    $lblStepDesc.Text  = $step.Desc

    $pnlRadios.Controls.Clear()
    $currentVal = $choices[$step.Key]
    $yOff = 0

    foreach ($opt in $step.Opts) {
        $rb = New-Object System.Windows.Forms.RadioButton
        $rb.SetBounds(0, $yOff, 380, 22)
        $rb.Text      = $opt.Label
        $rb.Font      = $fntBody
        $rb.ForeColor = $clrText
        $rb.BackColor = [System.Drawing.Color]::Transparent
        $rb.Checked   = ($opt.Val -eq $currentVal)
        $rb.Tag       = $opt.Val

        $lbl = New-Object System.Windows.Forms.Label
        $lbl.SetBounds(20, $yOff + 22, 360, 30)
        $lbl.Text      = $opt.Detail
        $lbl.Font      = $fntSmall
        $lbl.ForeColor = $clrSub
        $lbl.BackColor = [System.Drawing.Color]::Transparent

        $capturedOpt  = $opt
        $capturedStep = $step
        $capturedImgs = $step.Imgs
        $rb.Add_CheckedChanged({
            param($s, $e)
            if ($s.Checked) {
                $choices[$capturedStep.Key] = $s.Tag
                $imgIdx = [Array]::IndexOf(($capturedStep.Opts | ForEach-Object { $_.Val }), $s.Tag)
                $imgFile = if ($capturedImgs -and $imgIdx -ge 0 -and $imgIdx -lt $capturedImgs.Count) { $capturedImgs[$imgIdx] } else { $null }
                $img = Load-Asset $imgFile
                $old = $pic.Image
                if ($img) {
                    $pic.Image   = $img
                    $pic.Visible = $true
                    $lblNoPic.Visible = $false
                } else {
                    $pic.Image   = $null
                    $pic.Visible = $false
                    $lblNoPic.Visible = $true
                }
                if ($old) { $old.Dispose() }
            }
        }.GetNewClosure())

        $pnlRadios.Controls.Add($rb)
        $pnlRadios.Controls.Add($lbl)
        $yOff += 66
    }

    # Load preview for current selection
    $selIdx = [Array]::IndexOf(($step.Opts | ForEach-Object { $_.Val }), $currentVal)
    $imgFile = if ($step.Imgs -and $selIdx -ge 0 -and $selIdx -lt $step.Imgs.Count) { $step.Imgs[$selIdx] } else { $null }
    $img = Load-Asset $imgFile
    $old = $pic.Image
    if ($img) {
        $pic.Image   = $img
        $pic.Visible = $true
        $lblNoPic.Visible = $false
    } else {
        $pic.Image   = $null
        $pic.Visible = $false
        $lblNoPic.Visible = $true
    }
    if ($old) { $old.Dispose() }

    $btnBack.Visible    = ($idx -gt 0)
    $btnNext.Visible    = $true
    $btnInstall.Visible = $false
    $pnlLeft.Visible    = $true
    $pnlRight.Visible   = $true
    $pnlConfirm.Visible = $false
    Set-Dots
}

function Show-Confirm {
    $langLabel = switch ($choices.Language) { "chinese" {"Chinese"} "korean" {"Korean"} default {"Latin + Japanese"} }
    $mapsLabel = if ($choices.Maps -eq "smooth") { "Smooth" } else { "Sharp-scaled" }
    $saveLabel = if ($choices.Savefiles -eq "artwork") { "Artwork Backdrops" } else { "HD Original" }

    $lblConfirmBody.Text = @"
Your selections:

  Language     :  $langLabel
  Map Style    :  $mapsLabel
  Save Files   :  $saveLabel

Click Install to apply your choices.
Nova Chrysalia Launcher will then complete the installation.
"@
    $lblConfirmHdr.Text  = "Ready to install"
    $btnBack.Visible    = $true
    $pnlLeft.Visible    = $false
    $pnlRight.Visible   = $false
    $pnlConfirm.Visible = $true
    $btnNext.Visible    = $false
    $btnInstall.Visible = $true
    Set-Dots
}

function Navigate($delta) {
    $next = $script:page + $delta
    if ($next -lt 0) { return }
    if ($next -ge $steps.Count) {
        $script:page = $steps.Count
        Show-Confirm
        return
    }
    $script:page = $next
    Show-Step $script:page
}

# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------
function Run-Install {
    $btnInstall.Enabled = $false
    $btnBack.Enabled    = $false
    $lblConfirmBody.Text = "Applying your choices, please wait..."
    [System.Windows.Forms.Application]::DoEvents()

    # Remove any leftover mod files from a previous manual installation.
    if ($gameBinDir -and [System.IO.Directory]::Exists($gameBinDir)) {
        $lblConfirmBody.Text = "Checking for previous installation..."
        [System.Windows.Forms.Application]::DoEvents()
        foreach ($item in @("version.dll", "hd_textures")) {
            $target = [System.IO.Path]::Combine($gameBinDir, $item)
            if (Test-Path -LiteralPath $target) {
                Remove-Item -LiteralPath $target -Recurse -Force -ErrorAction SilentlyContinue
            }
        }
    }

    # Ensure destination exists
    if (-not [System.IO.Directory]::Exists($dataDir)) {
        $null = New-Item -ItemType Directory -Force -Path $dataDir
    }

    function Overlay($sub) {
        $s = Join-Path $sourceDir $sub
        if ([System.IO.Directory]::Exists($s)) {
            $null = robocopy $s $dataDir /E /NFL /NDL /NJH /NJS /NP
        } else {
            [System.Windows.Forms.MessageBox]::Show(
                "Warning: source folder not found:`n$s",
                "FF XIII HD Mod", "OK", "Warning")
        }
    }

    # Always copy base mod first
    Overlay "base"

    if ($choices.Language   -eq "chinese") { Overlay "fonts_chinese"      }
    if ($choices.Language   -eq "korean")  { Overlay "fonts_korean"       }
    if ($choices.Maps       -eq "smooth")  { Overlay "smooth_maps"        }
    if ($choices.Savefiles  -eq "artwork") { Overlay "artwork_savefiles"  }

    $langLabel = switch ($choices.Language) { "chinese" {"Chinese"} "korean" {"Korean"} default {"Latin + Japanese"} }
    $mapsLabel = if ($choices.Maps      -eq "smooth")  { "Smooth"           } else { "Sharp-scaled" }
    $saveLabel = if ($choices.Savefiles -eq "artwork") { "Artwork Backdrops" } else { "HD Original"  }

    $lblConfirmBody.Text = @"
Installation complete!

  Language     :  $langLabel
  Map Style    :  $mapsLabel
  Save Files   :  $saveLabel

You can now close this window.
Nova Chrysalia Launcher will continue the installation.
"@
    $lblConfirmHdr.Text = "Done"
    $btnInstall.Text    = "Close"
    $btnInstall.Enabled = $true
    $btnInstall.Add_Click({ $form.Close() })
}

# ---------------------------------------------------------------------------
# Wire up and launch
# ---------------------------------------------------------------------------
$btnBack.Add_Click(   { Navigate -1 })
$btnNext.Add_Click(   { Navigate  1 })
$btnInstall.Add_Click({ Run-Install  })

Show-Step 0
[System.Windows.Forms.Application]::Run($form)
